while (true) {
let Prototyp = prompt ("entre from C1 a c2");
if(Prototyp == "exit"){
alert ("Cette compétence n'existe pas")
break;
}

if (prototyp == "c1"){
    alert("maquetter un eapplication");
}else if (prototyp == "c2") {
    alert( "réalser une interface utilisateur web statique et adaptable");
}else if(prototyp == "c3"){
    alert("Développer une interface utilisateur web dynamique");
}else if(prototyp == "c4"){
    alert("Réaliser une interface utilisateur avec une solution de gestion de contenu ou e-commerce");
}else if(prototyp == "c5"){
    alert("Créer une base de données - niveau 1");
}else if (prototyp == "c6"){
    alert("Développer les composants d’accès aux données - niveau 1");
}else if(prototyp == "c7"){
    alert("Développer la partie back-end d’une application web ou web mobile - niveau 1");
}else if( Prototype == "C8"){
alert("Framwork FrontEnd (React, vueJs...)");
}else if (Prototype == "T1"){
    alert("Comprendre la démarche pédagogique à Solicode");
}else if (prototyp == "T2"){
    alert ("Collaboration & posture professionnelle");
}else if(prototyp == "T3"){
    alert("Gérer un projet avec Git & GitHub");
}
}






